version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
jobs:
  run-cypress:
    executor: cypress/default
    steps:
      - checkout # Checkout Your Project's Code From Github
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Cypress Tests
          command: npm test
workflows:
  end-to-end-tests:
    jobs:
      - run-cypress